/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as ApiAccountsLoginRouteImport } from './routes/api/accounts/login'
import { Route as ApiAccountsMeRouteImport } from './routes/api/accounts/me'
import { Route as ApiAccountsRegisterRouteImport } from './routes/api/accounts/register'
import { Route as ApiAppointmentsIndexRouteImport } from './routes/api/appointments/index'
import { Route as ApiDoctorDashboardRouteImport } from './routes/api/doctor/dashboard'
import { Route as ApiMessagesIndexRouteImport } from './routes/api/messages/index'
import { Route as ApiNotificationsAppointmentEmailRouteImport } from './routes/api/notifications/appointment-email'
import { Route as ApiPharmacyCreateCheckoutSessionRouteImport } from './routes/api/pharmacy/create-checkout-session'
import { Route as ApiRecordsIndexRouteImport } from './routes/api/records/index'
import { Route as ApiRecordsMigrateRouteImport } from './routes/api/records/migrate'
import { Route as ApiStripeConfirmBillPaymentRouteImport } from './routes/api/stripe/confirm-bill-payment'
import { Route as ApiStripeCreateCheckoutSessionRouteImport } from './routes/api/stripe/create-checkout-session'
import { Route as ApiStripeCreateMedicationCheckoutSessionRouteImport } from './routes/api/stripe/create-medication-checkout-session'
import { Route as ApiAdminAuditEventsIndexRouteImport } from './routes/api/admin/audit-events/index'
import { Route as ApiAdminPatientsIndexRouteImport } from './routes/api/admin/patients/index'
import { Route as ApiAdminPatientsIdRouteImport } from './routes/api/admin/patients/$id'
import { Route as ApiAdminSchedulesIndexRouteImport } from './routes/api/admin/schedules/index'
import { Route as ApiAppointmentsIdStatusRouteImport } from './routes/api/appointments/$id/status'
import { Route as ApiDoctorEncountersEncounterIdRouteImport } from './routes/api/doctor/encounters/$encounterId'
import { Route as ApiDoctorPatientsPatientIdRouteImport } from './routes/api/doctor/patients/$patientId'
import { Route as ApiMessagesConversationIdIndexRouteImport } from './routes/api/messages/$conversationId/index'
import { Route as ApiMessagesConversationIdReadRouteImport } from './routes/api/messages/$conversationId/read'
import { Route as ApiPharmacyCatalogIndexRouteImport } from './routes/api/pharmacy/catalog/index'
import { Route as ApiPharmacyCatalogIdRouteImport } from './routes/api/pharmacy/catalog/$id'
import { Route as ApiPharmacyOrdersIndexRouteImport } from './routes/api/pharmacy/orders/index'
import { Route as ApiRecordsEncounterIdIndexRouteImport } from './routes/api/records/$encounterId/index'
import { Route as ApiRecordsEncounterIdPatientDataRouteImport } from './routes/api/records/$encounterId/patient-data'
import { Route as ApiStripeCheckoutSessionSessionIdRouteImport } from './routes/api/stripe/checkout-session/$sessionId'
import { Route as ApiDoctorAppointmentsIdStatusRouteImport } from './routes/api/doctor/appointments/$id/status'
import { Route as ApiDoctorPatientsPatientIdFollowUpsRouteImport } from './routes/api/doctor/patients/$patientId/follow-ups'
import { Route as ApiPharmacyOrdersReferenceConfirmPaymentRouteImport } from './routes/api/pharmacy/orders/$reference/confirm-payment'
import { Route as ApiPharmacyOrdersReferenceReceivedRouteImport } from './routes/api/pharmacy/orders/$reference/received'
import { Route as ApiPharmacyOrdersReferenceStatusRouteImport } from './routes/api/pharmacy/orders/$reference/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsLoginRoute = ApiAccountsLoginRouteImport.update({
  id: '/api/accounts/login',
  path: '/api/accounts/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsMeRoute = ApiAccountsMeRouteImport.update({
  id: '/api/accounts/me',
  path: '/api/accounts/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRegisterRoute = ApiAccountsRegisterRouteImport.update({
  id: '/api/accounts/register',
  path: '/api/accounts/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppointmentsIndexRoute = ApiAppointmentsIndexRouteImport.update({
  id: '/api/appointments/',
  path: '/api/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoctorDashboardRoute = ApiDoctorDashboardRouteImport.update({
  id: '/api/doctor/dashboard',
  path: '/api/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesIndexRoute = ApiMessagesIndexRouteImport.update({
  id: '/api/messages/',
  path: '/api/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsAppointmentEmailRoute =
  ApiNotificationsAppointmentEmailRouteImport.update({
    id: '/api/notifications/appointment-email',
    path: '/api/notifications/appointment-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPharmacyCreateCheckoutSessionRoute =
  ApiPharmacyCreateCheckoutSessionRouteImport.update({
    id: '/api/pharmacy/create-checkout-session',
    path: '/api/pharmacy/create-checkout-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRecordsIndexRoute = ApiRecordsIndexRouteImport.update({
  id: '/api/records/',
  path: '/api/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsMigrateRoute = ApiRecordsMigrateRouteImport.update({
  id: '/api/records/migrate',
  path: '/api/records/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeConfirmBillPaymentRoute =
  ApiStripeConfirmBillPaymentRouteImport.update({
    id: '/api/stripe/confirm-bill-payment',
    path: '/api/stripe/confirm-bill-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeCreateCheckoutSessionRoute =
  ApiStripeCreateCheckoutSessionRouteImport.update({
    id: '/api/stripe/create-checkout-session',
    path: '/api/stripe/create-checkout-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeCreateMedicationCheckoutSessionRoute =
  ApiStripeCreateMedicationCheckoutSessionRouteImport.update({
    id: '/api/stripe/create-medication-checkout-session',
    path: '/api/stripe/create-medication-checkout-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAuditEventsIndexRoute =
  ApiAdminAuditEventsIndexRouteImport.update({
    id: '/api/admin/audit-events/',
    path: '/api/admin/audit-events/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPatientsIndexRoute = ApiAdminPatientsIndexRouteImport.update({
  id: '/api/admin/patients/',
  path: '/api/admin/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPatientsIdRoute = ApiAdminPatientsIdRouteImport.update({
  id: '/api/admin/patients/$id',
  path: '/api/admin/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSchedulesIndexRoute = ApiAdminSchedulesIndexRouteImport.update({
  id: '/api/admin/schedules/',
  path: '/api/admin/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppointmentsIdStatusRoute = ApiAppointmentsIdStatusRouteImport.update({
  id: '/api/appointments/$id/status',
  path: '/api/appointments/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoctorEncountersEncounterIdRoute =
  ApiDoctorEncountersEncounterIdRouteImport.update({
    id: '/api/doctor/encounters/$encounterId',
    path: '/api/doctor/encounters/$encounterId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDoctorPatientsPatientIdRoute =
  ApiDoctorPatientsPatientIdRouteImport.update({
    id: '/api/doctor/patients/$patientId',
    path: '/api/doctor/patients/$patientId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMessagesConversationIdIndexRoute =
  ApiMessagesConversationIdIndexRouteImport.update({
    id: '/api/messages/$conversationId/',
    path: '/api/messages/$conversationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMessagesConversationIdReadRoute =
  ApiMessagesConversationIdReadRouteImport.update({
    id: '/api/messages/$conversationId/read',
    path: '/api/messages/$conversationId/read',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPharmacyCatalogIndexRoute = ApiPharmacyCatalogIndexRouteImport.update({
  id: '/api/pharmacy/catalog/',
  path: '/api/pharmacy/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPharmacyCatalogIdRoute = ApiPharmacyCatalogIdRouteImport.update({
  id: '/api/pharmacy/catalog/$id',
  path: '/api/pharmacy/catalog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPharmacyOrdersIndexRoute = ApiPharmacyOrdersIndexRouteImport.update({
  id: '/api/pharmacy/orders/',
  path: '/api/pharmacy/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsEncounterIdIndexRoute =
  ApiRecordsEncounterIdIndexRouteImport.update({
    id: '/api/records/$encounterId/',
    path: '/api/records/$encounterId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRecordsEncounterIdPatientDataRoute =
  ApiRecordsEncounterIdPatientDataRouteImport.update({
    id: '/api/records/$encounterId/patient-data',
    path: '/api/records/$encounterId/patient-data',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeCheckoutSessionSessionIdRoute =
  ApiStripeCheckoutSessionSessionIdRouteImport.update({
    id: '/api/stripe/checkout-session/$sessionId',
    path: '/api/stripe/checkout-session/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDoctorAppointmentsIdStatusRoute =
  ApiDoctorAppointmentsIdStatusRouteImport.update({
    id: '/api/doctor/appointments/$id/status',
    path: '/api/doctor/appointments/$id/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDoctorPatientsPatientIdFollowUpsRoute =
  ApiDoctorPatientsPatientIdFollowUpsRouteImport.update({
    id: '/follow-ups',
    path: '/follow-ups',
    getParentRoute: () => ApiDoctorPatientsPatientIdRoute,
  } as any)
const ApiPharmacyOrdersReferenceConfirmPaymentRoute =
  ApiPharmacyOrdersReferenceConfirmPaymentRouteImport.update({
    id: '/api/pharmacy/orders/$reference/confirm-payment',
    path: '/api/pharmacy/orders/$reference/confirm-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPharmacyOrdersReferenceReceivedRoute =
  ApiPharmacyOrdersReferenceReceivedRouteImport.update({
    id: '/api/pharmacy/orders/$reference/received',
    path: '/api/pharmacy/orders/$reference/received',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPharmacyOrdersReferenceStatusRoute =
  ApiPharmacyOrdersReferenceStatusRouteImport.update({
    id: '/api/pharmacy/orders/$reference/status',
    path: '/api/pharmacy/orders/$reference/status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/landing': typeof LandingRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/accounts/login': typeof ApiAccountsLoginRoute
  '/api/accounts/me': typeof ApiAccountsMeRoute
  '/api/accounts/register': typeof ApiAccountsRegisterRoute
  '/api/doctor/dashboard': typeof ApiDoctorDashboardRoute
  '/api/notifications/appointment-email': typeof ApiNotificationsAppointmentEmailRoute
  '/api/pharmacy/create-checkout-session': typeof ApiPharmacyCreateCheckoutSessionRoute
  '/api/records/migrate': typeof ApiRecordsMigrateRoute
  '/api/stripe/confirm-bill-payment': typeof ApiStripeConfirmBillPaymentRoute
  '/api/stripe/create-checkout-session': typeof ApiStripeCreateCheckoutSessionRoute
  '/api/stripe/create-medication-checkout-session': typeof ApiStripeCreateMedicationCheckoutSessionRoute
  '/api/appointments/': typeof ApiAppointmentsIndexRoute
  '/api/messages/': typeof ApiMessagesIndexRoute
  '/api/records/': typeof ApiRecordsIndexRoute
  '/api/admin/patients/$id': typeof ApiAdminPatientsIdRoute
  '/api/appointments/$id/status': typeof ApiAppointmentsIdStatusRoute
  '/api/doctor/encounters/$encounterId': typeof ApiDoctorEncountersEncounterIdRoute
  '/api/doctor/patients/$patientId': typeof ApiDoctorPatientsPatientIdRouteWithChildren
  '/api/messages/$conversationId/read': typeof ApiMessagesConversationIdReadRoute
  '/api/pharmacy/catalog/$id': typeof ApiPharmacyCatalogIdRoute
  '/api/records/$encounterId/patient-data': typeof ApiRecordsEncounterIdPatientDataRoute
  '/api/stripe/checkout-session/$sessionId': typeof ApiStripeCheckoutSessionSessionIdRoute
  '/api/admin/audit-events/': typeof ApiAdminAuditEventsIndexRoute
  '/api/admin/patients/': typeof ApiAdminPatientsIndexRoute
  '/api/admin/schedules/': typeof ApiAdminSchedulesIndexRoute
  '/api/messages/$conversationId/': typeof ApiMessagesConversationIdIndexRoute
  '/api/pharmacy/catalog/': typeof ApiPharmacyCatalogIndexRoute
  '/api/pharmacy/orders/': typeof ApiPharmacyOrdersIndexRoute
  '/api/records/$encounterId/': typeof ApiRecordsEncounterIdIndexRoute
  '/api/doctor/appointments/$id/status': typeof ApiDoctorAppointmentsIdStatusRoute
  '/api/doctor/patients/$patientId/follow-ups': typeof ApiDoctorPatientsPatientIdFollowUpsRoute
  '/api/pharmacy/orders/$reference/confirm-payment': typeof ApiPharmacyOrdersReferenceConfirmPaymentRoute
  '/api/pharmacy/orders/$reference/received': typeof ApiPharmacyOrdersReferenceReceivedRoute
  '/api/pharmacy/orders/$reference/status': typeof ApiPharmacyOrdersReferenceStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/landing': typeof LandingRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/accounts/login': typeof ApiAccountsLoginRoute
  '/api/accounts/me': typeof ApiAccountsMeRoute
  '/api/accounts/register': typeof ApiAccountsRegisterRoute
  '/api/doctor/dashboard': typeof ApiDoctorDashboardRoute
  '/api/notifications/appointment-email': typeof ApiNotificationsAppointmentEmailRoute
  '/api/pharmacy/create-checkout-session': typeof ApiPharmacyCreateCheckoutSessionRoute
  '/api/records/migrate': typeof ApiRecordsMigrateRoute
  '/api/stripe/confirm-bill-payment': typeof ApiStripeConfirmBillPaymentRoute
  '/api/stripe/create-checkout-session': typeof ApiStripeCreateCheckoutSessionRoute
  '/api/stripe/create-medication-checkout-session': typeof ApiStripeCreateMedicationCheckoutSessionRoute
  '/api/appointments': typeof ApiAppointmentsIndexRoute
  '/api/messages': typeof ApiMessagesIndexRoute
  '/api/records': typeof ApiRecordsIndexRoute
  '/api/admin/patients/$id': typeof ApiAdminPatientsIdRoute
  '/api/appointments/$id/status': typeof ApiAppointmentsIdStatusRoute
  '/api/doctor/encounters/$encounterId': typeof ApiDoctorEncountersEncounterIdRoute
  '/api/doctor/patients/$patientId': typeof ApiDoctorPatientsPatientIdRouteWithChildren
  '/api/messages/$conversationId/read': typeof ApiMessagesConversationIdReadRoute
  '/api/pharmacy/catalog/$id': typeof ApiPharmacyCatalogIdRoute
  '/api/records/$encounterId/patient-data': typeof ApiRecordsEncounterIdPatientDataRoute
  '/api/stripe/checkout-session/$sessionId': typeof ApiStripeCheckoutSessionSessionIdRoute
  '/api/admin/audit-events': typeof ApiAdminAuditEventsIndexRoute
  '/api/admin/patients': typeof ApiAdminPatientsIndexRoute
  '/api/admin/schedules': typeof ApiAdminSchedulesIndexRoute
  '/api/messages/$conversationId': typeof ApiMessagesConversationIdIndexRoute
  '/api/pharmacy/catalog': typeof ApiPharmacyCatalogIndexRoute
  '/api/pharmacy/orders': typeof ApiPharmacyOrdersIndexRoute
  '/api/records/$encounterId': typeof ApiRecordsEncounterIdIndexRoute
  '/api/doctor/appointments/$id/status': typeof ApiDoctorAppointmentsIdStatusRoute
  '/api/doctor/patients/$patientId/follow-ups': typeof ApiDoctorPatientsPatientIdFollowUpsRoute
  '/api/pharmacy/orders/$reference/confirm-payment': typeof ApiPharmacyOrdersReferenceConfirmPaymentRoute
  '/api/pharmacy/orders/$reference/received': typeof ApiPharmacyOrdersReferenceReceivedRoute
  '/api/pharmacy/orders/$reference/status': typeof ApiPharmacyOrdersReferenceStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/landing': typeof LandingRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/accounts/login': typeof ApiAccountsLoginRoute
  '/api/accounts/me': typeof ApiAccountsMeRoute
  '/api/accounts/register': typeof ApiAccountsRegisterRoute
  '/api/doctor/dashboard': typeof ApiDoctorDashboardRoute
  '/api/notifications/appointment-email': typeof ApiNotificationsAppointmentEmailRoute
  '/api/pharmacy/create-checkout-session': typeof ApiPharmacyCreateCheckoutSessionRoute
  '/api/records/migrate': typeof ApiRecordsMigrateRoute
  '/api/stripe/confirm-bill-payment': typeof ApiStripeConfirmBillPaymentRoute
  '/api/stripe/create-checkout-session': typeof ApiStripeCreateCheckoutSessionRoute
  '/api/stripe/create-medication-checkout-session': typeof ApiStripeCreateMedicationCheckoutSessionRoute
  '/api/appointments/': typeof ApiAppointmentsIndexRoute
  '/api/messages/': typeof ApiMessagesIndexRoute
  '/api/records/': typeof ApiRecordsIndexRoute
  '/api/admin/patients/$id': typeof ApiAdminPatientsIdRoute
  '/api/appointments/$id/status': typeof ApiAppointmentsIdStatusRoute
  '/api/doctor/encounters/$encounterId': typeof ApiDoctorEncountersEncounterIdRoute
  '/api/doctor/patients/$patientId': typeof ApiDoctorPatientsPatientIdRouteWithChildren
  '/api/messages/$conversationId/read': typeof ApiMessagesConversationIdReadRoute
  '/api/pharmacy/catalog/$id': typeof ApiPharmacyCatalogIdRoute
  '/api/records/$encounterId/patient-data': typeof ApiRecordsEncounterIdPatientDataRoute
  '/api/stripe/checkout-session/$sessionId': typeof ApiStripeCheckoutSessionSessionIdRoute
  '/api/admin/audit-events/': typeof ApiAdminAuditEventsIndexRoute
  '/api/admin/patients/': typeof ApiAdminPatientsIndexRoute
  '/api/admin/schedules/': typeof ApiAdminSchedulesIndexRoute
  '/api/messages/$conversationId/': typeof ApiMessagesConversationIdIndexRoute
  '/api/pharmacy/catalog/': typeof ApiPharmacyCatalogIndexRoute
  '/api/pharmacy/orders/': typeof ApiPharmacyOrdersIndexRoute
  '/api/records/$encounterId/': typeof ApiRecordsEncounterIdIndexRoute
  '/api/doctor/appointments/$id/status': typeof ApiDoctorAppointmentsIdStatusRoute
  '/api/doctor/patients/$patientId/follow-ups': typeof ApiDoctorPatientsPatientIdFollowUpsRoute
  '/api/pharmacy/orders/$reference/confirm-payment': typeof ApiPharmacyOrdersReferenceConfirmPaymentRoute
  '/api/pharmacy/orders/$reference/received': typeof ApiPharmacyOrdersReferenceReceivedRoute
  '/api/pharmacy/orders/$reference/status': typeof ApiPharmacyOrdersReferenceStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/landing'
    | '/api/healthz'
    | '/api/accounts/login'
    | '/api/accounts/me'
    | '/api/accounts/register'
    | '/api/doctor/dashboard'
    | '/api/notifications/appointment-email'
    | '/api/pharmacy/create-checkout-session'
    | '/api/records/migrate'
    | '/api/stripe/confirm-bill-payment'
    | '/api/stripe/create-checkout-session'
    | '/api/stripe/create-medication-checkout-session'
    | '/api/appointments/'
    | '/api/messages/'
    | '/api/records/'
    | '/api/admin/patients/$id'
    | '/api/appointments/$id/status'
    | '/api/doctor/encounters/$encounterId'
    | '/api/doctor/patients/$patientId'
    | '/api/messages/$conversationId/read'
    | '/api/pharmacy/catalog/$id'
    | '/api/records/$encounterId/patient-data'
    | '/api/stripe/checkout-session/$sessionId'
    | '/api/admin/audit-events/'
    | '/api/admin/patients/'
    | '/api/admin/schedules/'
    | '/api/messages/$conversationId/'
    | '/api/pharmacy/catalog/'
    | '/api/pharmacy/orders/'
    | '/api/records/$encounterId/'
    | '/api/doctor/appointments/$id/status'
    | '/api/doctor/patients/$patientId/follow-ups'
    | '/api/pharmacy/orders/$reference/confirm-payment'
    | '/api/pharmacy/orders/$reference/received'
    | '/api/pharmacy/orders/$reference/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/landing'
    | '/api/healthz'
    | '/api/accounts/login'
    | '/api/accounts/me'
    | '/api/accounts/register'
    | '/api/doctor/dashboard'
    | '/api/notifications/appointment-email'
    | '/api/pharmacy/create-checkout-session'
    | '/api/records/migrate'
    | '/api/stripe/confirm-bill-payment'
    | '/api/stripe/create-checkout-session'
    | '/api/stripe/create-medication-checkout-session'
    | '/api/appointments'
    | '/api/messages'
    | '/api/records'
    | '/api/admin/patients/$id'
    | '/api/appointments/$id/status'
    | '/api/doctor/encounters/$encounterId'
    | '/api/doctor/patients/$patientId'
    | '/api/messages/$conversationId/read'
    | '/api/pharmacy/catalog/$id'
    | '/api/records/$encounterId/patient-data'
    | '/api/stripe/checkout-session/$sessionId'
    | '/api/admin/audit-events'
    | '/api/admin/patients'
    | '/api/admin/schedules'
    | '/api/messages/$conversationId'
    | '/api/pharmacy/catalog'
    | '/api/pharmacy/orders'
    | '/api/records/$encounterId'
    | '/api/doctor/appointments/$id/status'
    | '/api/doctor/patients/$patientId/follow-ups'
    | '/api/pharmacy/orders/$reference/confirm-payment'
    | '/api/pharmacy/orders/$reference/received'
    | '/api/pharmacy/orders/$reference/status'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/landing'
    | '/api/healthz'
    | '/api/accounts/login'
    | '/api/accounts/me'
    | '/api/accounts/register'
    | '/api/doctor/dashboard'
    | '/api/notifications/appointment-email'
    | '/api/pharmacy/create-checkout-session'
    | '/api/records/migrate'
    | '/api/stripe/confirm-bill-payment'
    | '/api/stripe/create-checkout-session'
    | '/api/stripe/create-medication-checkout-session'
    | '/api/appointments/'
    | '/api/messages/'
    | '/api/records/'
    | '/api/admin/patients/$id'
    | '/api/appointments/$id/status'
    | '/api/doctor/encounters/$encounterId'
    | '/api/doctor/patients/$patientId'
    | '/api/messages/$conversationId/read'
    | '/api/pharmacy/catalog/$id'
    | '/api/records/$encounterId/patient-data'
    | '/api/stripe/checkout-session/$sessionId'
    | '/api/admin/audit-events/'
    | '/api/admin/patients/'
    | '/api/admin/schedules/'
    | '/api/messages/$conversationId/'
    | '/api/pharmacy/catalog/'
    | '/api/pharmacy/orders/'
    | '/api/records/$encounterId/'
    | '/api/doctor/appointments/$id/status'
    | '/api/doctor/patients/$patientId/follow-ups'
    | '/api/pharmacy/orders/$reference/confirm-payment'
    | '/api/pharmacy/orders/$reference/received'
    | '/api/pharmacy/orders/$reference/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LandingRoute: typeof LandingRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiAccountsLoginRoute: typeof ApiAccountsLoginRoute
  ApiAccountsMeRoute: typeof ApiAccountsMeRoute
  ApiAccountsRegisterRoute: typeof ApiAccountsRegisterRoute
  ApiDoctorDashboardRoute: typeof ApiDoctorDashboardRoute
  ApiNotificationsAppointmentEmailRoute: typeof ApiNotificationsAppointmentEmailRoute
  ApiPharmacyCreateCheckoutSessionRoute: typeof ApiPharmacyCreateCheckoutSessionRoute
  ApiRecordsMigrateRoute: typeof ApiRecordsMigrateRoute
  ApiStripeConfirmBillPaymentRoute: typeof ApiStripeConfirmBillPaymentRoute
  ApiStripeCreateCheckoutSessionRoute: typeof ApiStripeCreateCheckoutSessionRoute
  ApiStripeCreateMedicationCheckoutSessionRoute: typeof ApiStripeCreateMedicationCheckoutSessionRoute
  ApiAppointmentsIndexRoute: typeof ApiAppointmentsIndexRoute
  ApiMessagesIndexRoute: typeof ApiMessagesIndexRoute
  ApiRecordsIndexRoute: typeof ApiRecordsIndexRoute
  ApiAdminPatientsIdRoute: typeof ApiAdminPatientsIdRoute
  ApiAppointmentsIdStatusRoute: typeof ApiAppointmentsIdStatusRoute
  ApiDoctorEncountersEncounterIdRoute: typeof ApiDoctorEncountersEncounterIdRoute
  ApiDoctorPatientsPatientIdRoute: typeof ApiDoctorPatientsPatientIdRouteWithChildren
  ApiMessagesConversationIdReadRoute: typeof ApiMessagesConversationIdReadRoute
  ApiPharmacyCatalogIdRoute: typeof ApiPharmacyCatalogIdRoute
  ApiRecordsEncounterIdPatientDataRoute: typeof ApiRecordsEncounterIdPatientDataRoute
  ApiStripeCheckoutSessionSessionIdRoute: typeof ApiStripeCheckoutSessionSessionIdRoute
  ApiAdminAuditEventsIndexRoute: typeof ApiAdminAuditEventsIndexRoute
  ApiAdminPatientsIndexRoute: typeof ApiAdminPatientsIndexRoute
  ApiAdminSchedulesIndexRoute: typeof ApiAdminSchedulesIndexRoute
  ApiMessagesConversationIdIndexRoute: typeof ApiMessagesConversationIdIndexRoute
  ApiPharmacyCatalogIndexRoute: typeof ApiPharmacyCatalogIndexRoute
  ApiPharmacyOrdersIndexRoute: typeof ApiPharmacyOrdersIndexRoute
  ApiRecordsEncounterIdIndexRoute: typeof ApiRecordsEncounterIdIndexRoute
  ApiDoctorAppointmentsIdStatusRoute: typeof ApiDoctorAppointmentsIdStatusRoute
  ApiPharmacyOrdersReferenceConfirmPaymentRoute: typeof ApiPharmacyOrdersReferenceConfirmPaymentRoute
  ApiPharmacyOrdersReferenceReceivedRoute: typeof ApiPharmacyOrdersReferenceReceivedRoute
  ApiPharmacyOrdersReferenceStatusRoute: typeof ApiPharmacyOrdersReferenceStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/login': {
      id: '/api/accounts/login'
      path: '/api/accounts/login'
      fullPath: '/api/accounts/login'
      preLoaderRoute: typeof ApiAccountsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/me': {
      id: '/api/accounts/me'
      path: '/api/accounts/me'
      fullPath: '/api/accounts/me'
      preLoaderRoute: typeof ApiAccountsMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/register': {
      id: '/api/accounts/register'
      path: '/api/accounts/register'
      fullPath: '/api/accounts/register'
      preLoaderRoute: typeof ApiAccountsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointments/': {
      id: '/api/appointments/'
      path: '/api/appointments'
      fullPath: '/api/appointments/'
      preLoaderRoute: typeof ApiAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor/dashboard': {
      id: '/api/doctor/dashboard'
      path: '/api/doctor/dashboard'
      fullPath: '/api/doctor/dashboard'
      preLoaderRoute: typeof ApiDoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/': {
      id: '/api/messages/'
      path: '/api/messages'
      fullPath: '/api/messages/'
      preLoaderRoute: typeof ApiMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/appointment-email': {
      id: '/api/notifications/appointment-email'
      path: '/api/notifications/appointment-email'
      fullPath: '/api/notifications/appointment-email'
      preLoaderRoute: typeof ApiNotificationsAppointmentEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pharmacy/create-checkout-session': {
      id: '/api/pharmacy/create-checkout-session'
      path: '/api/pharmacy/create-checkout-session'
      fullPath: '/api/pharmacy/create-checkout-session'
      preLoaderRoute: typeof ApiPharmacyCreateCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/': {
      id: '/api/records/'
      path: '/api/records'
      fullPath: '/api/records/'
      preLoaderRoute: typeof ApiRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/migrate': {
      id: '/api/records/migrate'
      path: '/api/records/migrate'
      fullPath: '/api/records/migrate'
      preLoaderRoute: typeof ApiRecordsMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/confirm-bill-payment': {
      id: '/api/stripe/confirm-bill-payment'
      path: '/api/stripe/confirm-bill-payment'
      fullPath: '/api/stripe/confirm-bill-payment'
      preLoaderRoute: typeof ApiStripeConfirmBillPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/create-checkout-session': {
      id: '/api/stripe/create-checkout-session'
      path: '/api/stripe/create-checkout-session'
      fullPath: '/api/stripe/create-checkout-session'
      preLoaderRoute: typeof ApiStripeCreateCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/create-medication-checkout-session': {
      id: '/api/stripe/create-medication-checkout-session'
      path: '/api/stripe/create-medication-checkout-session'
      fullPath: '/api/stripe/create-medication-checkout-session'
      preLoaderRoute: typeof ApiStripeCreateMedicationCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit-events/': {
      id: '/api/admin/audit-events/'
      path: '/api/admin/audit-events'
      fullPath: '/api/admin/audit-events/'
      preLoaderRoute: typeof ApiAdminAuditEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/patients/': {
      id: '/api/admin/patients/'
      path: '/api/admin/patients'
      fullPath: '/api/admin/patients/'
      preLoaderRoute: typeof ApiAdminPatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/patients/$id': {
      id: '/api/admin/patients/$id'
      path: '/api/admin/patients/$id'
      fullPath: '/api/admin/patients/$id'
      preLoaderRoute: typeof ApiAdminPatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/schedules/': {
      id: '/api/admin/schedules/'
      path: '/api/admin/schedules'
      fullPath: '/api/admin/schedules/'
      preLoaderRoute: typeof ApiAdminSchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointments/$id/status': {
      id: '/api/appointments/$id/status'
      path: '/api/appointments/$id/status'
      fullPath: '/api/appointments/$id/status'
      preLoaderRoute: typeof ApiAppointmentsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor/encounters/$encounterId': {
      id: '/api/doctor/encounters/$encounterId'
      path: '/api/doctor/encounters/$encounterId'
      fullPath: '/api/doctor/encounters/$encounterId'
      preLoaderRoute: typeof ApiDoctorEncountersEncounterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor/patients/$patientId': {
      id: '/api/doctor/patients/$patientId'
      path: '/api/doctor/patients/$patientId'
      fullPath: '/api/doctor/patients/$patientId'
      preLoaderRoute: typeof ApiDoctorPatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/$conversationId/': {
      id: '/api/messages/$conversationId/'
      path: '/api/messages/$conversationId'
      fullPath: '/api/messages/$conversationId/'
      preLoaderRoute: typeof ApiMessagesConversationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/$conversationId/read': {
      id: '/api/messages/$conversationId/read'
      path: '/api/messages/$conversationId/read'
      fullPath: '/api/messages/$conversationId/read'
      preLoaderRoute: typeof ApiMessagesConversationIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pharmacy/catalog/': {
      id: '/api/pharmacy/catalog/'
      path: '/api/pharmacy/catalog'
      fullPath: '/api/pharmacy/catalog/'
      preLoaderRoute: typeof ApiPharmacyCatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pharmacy/catalog/$id': {
      id: '/api/pharmacy/catalog/$id'
      path: '/api/pharmacy/catalog/$id'
      fullPath: '/api/pharmacy/catalog/$id'
      preLoaderRoute: typeof ApiPharmacyCatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pharmacy/orders/': {
      id: '/api/pharmacy/orders/'
      path: '/api/pharmacy/orders'
      fullPath: '/api/pharmacy/orders/'
      preLoaderRoute: typeof ApiPharmacyOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/$encounterId/': {
      id: '/api/records/$encounterId/'
      path: '/api/records/$encounterId'
      fullPath: '/api/records/$encounterId/'
      preLoaderRoute: typeof ApiRecordsEncounterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/$encounterId/patient-data': {
      id: '/api/records/$encounterId/patient-data'
      path: '/api/records/$encounterId/patient-data'
      fullPath: '/api/records/$encounterId/patient-data'
      preLoaderRoute: typeof ApiRecordsEncounterIdPatientDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout-session/$sessionId': {
      id: '/api/stripe/checkout-session/$sessionId'
      path: '/api/stripe/checkout-session/$sessionId'
      fullPath: '/api/stripe/checkout-session/$sessionId'
      preLoaderRoute: typeof ApiStripeCheckoutSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor/appointments/$id/status': {
      id: '/api/doctor/appointments/$id/status'
      path: '/api/doctor/appointments/$id/status'
      fullPath: '/api/doctor/appointments/$id/status'
      preLoaderRoute: typeof ApiDoctorAppointmentsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doctor/patients/$patientId/follow-ups': {
      id: '/api/doctor/patients/$patientId/follow-ups'
      path: '/follow-ups'
      fullPath: '/api/doctor/patients/$patientId/follow-ups'
      preLoaderRoute: typeof ApiDoctorPatientsPatientIdFollowUpsRouteImport
      parentRoute: typeof ApiDoctorPatientsPatientIdRoute
    }
    '/api/pharmacy/orders/$reference/confirm-payment': {
      id: '/api/pharmacy/orders/$reference/confirm-payment'
      path: '/api/pharmacy/orders/$reference/confirm-payment'
      fullPath: '/api/pharmacy/orders/$reference/confirm-payment'
      preLoaderRoute: typeof ApiPharmacyOrdersReferenceConfirmPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pharmacy/orders/$reference/received': {
      id: '/api/pharmacy/orders/$reference/received'
      path: '/api/pharmacy/orders/$reference/received'
      fullPath: '/api/pharmacy/orders/$reference/received'
      preLoaderRoute: typeof ApiPharmacyOrdersReferenceReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pharmacy/orders/$reference/status': {
      id: '/api/pharmacy/orders/$reference/status'
      path: '/api/pharmacy/orders/$reference/status'
      fullPath: '/api/pharmacy/orders/$reference/status'
      preLoaderRoute: typeof ApiPharmacyOrdersReferenceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDoctorPatientsPatientIdRouteChildren {
  ApiDoctorPatientsPatientIdFollowUpsRoute: typeof ApiDoctorPatientsPatientIdFollowUpsRoute
}

const ApiDoctorPatientsPatientIdRouteChildren: ApiDoctorPatientsPatientIdRouteChildren =
  {
    ApiDoctorPatientsPatientIdFollowUpsRoute:
      ApiDoctorPatientsPatientIdFollowUpsRoute,
  }

const ApiDoctorPatientsPatientIdRouteWithChildren =
  ApiDoctorPatientsPatientIdRoute._addFileChildren(
    ApiDoctorPatientsPatientIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LandingRoute: LandingRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiAccountsLoginRoute: ApiAccountsLoginRoute,
  ApiAccountsMeRoute: ApiAccountsMeRoute,
  ApiAccountsRegisterRoute: ApiAccountsRegisterRoute,
  ApiDoctorDashboardRoute: ApiDoctorDashboardRoute,
  ApiNotificationsAppointmentEmailRoute: ApiNotificationsAppointmentEmailRoute,
  ApiPharmacyCreateCheckoutSessionRoute: ApiPharmacyCreateCheckoutSessionRoute,
  ApiRecordsMigrateRoute: ApiRecordsMigrateRoute,
  ApiStripeConfirmBillPaymentRoute: ApiStripeConfirmBillPaymentRoute,
  ApiStripeCreateCheckoutSessionRoute: ApiStripeCreateCheckoutSessionRoute,
  ApiStripeCreateMedicationCheckoutSessionRoute:
    ApiStripeCreateMedicationCheckoutSessionRoute,
  ApiAppointmentsIndexRoute: ApiAppointmentsIndexRoute,
  ApiMessagesIndexRoute: ApiMessagesIndexRoute,
  ApiRecordsIndexRoute: ApiRecordsIndexRoute,
  ApiAdminPatientsIdRoute: ApiAdminPatientsIdRoute,
  ApiAppointmentsIdStatusRoute: ApiAppointmentsIdStatusRoute,
  ApiDoctorEncountersEncounterIdRoute: ApiDoctorEncountersEncounterIdRoute,
  ApiDoctorPatientsPatientIdRoute: ApiDoctorPatientsPatientIdRouteWithChildren,
  ApiMessagesConversationIdReadRoute: ApiMessagesConversationIdReadRoute,
  ApiPharmacyCatalogIdRoute: ApiPharmacyCatalogIdRoute,
  ApiRecordsEncounterIdPatientDataRoute: ApiRecordsEncounterIdPatientDataRoute,
  ApiStripeCheckoutSessionSessionIdRoute:
    ApiStripeCheckoutSessionSessionIdRoute,
  ApiAdminAuditEventsIndexRoute: ApiAdminAuditEventsIndexRoute,
  ApiAdminPatientsIndexRoute: ApiAdminPatientsIndexRoute,
  ApiAdminSchedulesIndexRoute: ApiAdminSchedulesIndexRoute,
  ApiMessagesConversationIdIndexRoute: ApiMessagesConversationIdIndexRoute,
  ApiPharmacyCatalogIndexRoute: ApiPharmacyCatalogIndexRoute,
  ApiPharmacyOrdersIndexRoute: ApiPharmacyOrdersIndexRoute,
  ApiRecordsEncounterIdIndexRoute: ApiRecordsEncounterIdIndexRoute,
  ApiDoctorAppointmentsIdStatusRoute: ApiDoctorAppointmentsIdStatusRoute,
  ApiPharmacyOrdersReferenceConfirmPaymentRoute:
    ApiPharmacyOrdersReferenceConfirmPaymentRoute,
  ApiPharmacyOrdersReferenceReceivedRoute:
    ApiPharmacyOrdersReferenceReceivedRoute,
  ApiPharmacyOrdersReferenceStatusRoute: ApiPharmacyOrdersReferenceStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
